// This file is generated by rust-protobuf 2.11.0. Do not edit
// @generated

// https://github.com/rust-lang/rust-clippy/issues/702
#![allow(unknown_lints)]
#![allow(clippy::all)]

#![cfg_attr(rustfmt, rustfmt_skip)]

#![allow(box_pointers)]
#![allow(dead_code)]
#![allow(missing_docs)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(trivial_casts)]
#![allow(unsafe_code)]
#![allow(unused_imports)]
#![allow(unused_results)]
//! Generated file from `recon_mobile_e2.proto`

use protobuf::Message as Message_imported_for_functions;
use protobuf::ProtobufEnum as ProtobufEnum_imported_for_functions;

/// Generated files are compatible only with the same version
/// of protobuf runtime.
// const _PROTOBUF_VERSION_CHECK: () = ::protobuf::VERSION_2_11_0;

#[derive(PartialEq, Clone, Default)]
pub struct OutputAccount {
    // message fields
    pub datetime: i64,
    pub row_id: f64,
    pub merchant_code: ::std::string::String,
    pub service_account_id: ::std::string::String,
    pub tx_reference: ::std::string::String,
    pub tx_reference1: ::std::string::String,
    pub amount: f64,
    pub status: ::std::string::String,
    pub trx_type: ::std::string::String,
    pub status_description: ::std::string::String,
    pub trx_source: ::std::string::String,
    pub biller_status: ::std::string::String,
    pub country: ::std::string::String,
    pub discount_amount: f64,
    pub amount_txn: f64,
    pub access_mode: ::std::string::String,
    pub date: i64,
    pub time: i64,
    // special fields
    pub unknown_fields: ::protobuf::UnknownFields,
    pub cached_size: ::protobuf::CachedSize,
}

impl<'a> ::std::default::Default for &'a OutputAccount {
    fn default() -> &'a OutputAccount {
        <OutputAccount as ::protobuf::Message>::default_instance()
    }
}

impl OutputAccount {
    pub fn new() -> OutputAccount {
        ::std::default::Default::default()
    }

    // int64 datetime = 1;

    pub fn get_datetime(&self) -> i64 {
        self.datetime
    }
    pub fn clear_datetime(&mut self) {
        self.datetime = 0;
    }

    // Param is passed by value, moved
    pub fn set_datetime(&mut self, v: i64) {
        self.datetime = v;
    }

    // double row_id = 2;

    pub fn get_row_id(&self) -> f64 {
        self.row_id
    }
    pub fn clear_row_id(&mut self) {
        self.row_id = 0.;
    }

    // Param is passed by value, moved
    pub fn set_row_id(&mut self, v: f64) {
        self.row_id = v;
    }

    // string merchant_code = 3;

    pub fn get_merchant_code(&self) -> &str {
        &self.merchant_code
    }
    pub fn clear_merchant_code(&mut self) {
        self.merchant_code.clear();
    }

    // Param is passed by value, moved
    pub fn set_merchant_code(&mut self, v: ::std::string::String) {
        self.merchant_code = v;
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_merchant_code(&mut self) -> &mut ::std::string::String {
        &mut self.merchant_code
    }

    // Take field
    pub fn take_merchant_code(&mut self) -> ::std::string::String {
        ::std::mem::replace(&mut self.merchant_code, ::std::string::String::new())
    }

    // string service_account_id = 4;

    pub fn get_service_account_id(&self) -> &str {
        &self.service_account_id
    }
    pub fn clear_service_account_id(&mut self) {
        self.service_account_id.clear();
    }

    // Param is passed by value, moved
    pub fn set_service_account_id(&mut self, v: ::std::string::String) {
        self.service_account_id = v;
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_service_account_id(&mut self) -> &mut ::std::string::String {
        &mut self.service_account_id
    }

    // Take field
    pub fn take_service_account_id(&mut self) -> ::std::string::String {
        ::std::mem::replace(&mut self.service_account_id, ::std::string::String::new())
    }

    // string tx_reference = 5;

    pub fn get_tx_reference(&self) -> &str {
        &self.tx_reference
    }
    pub fn clear_tx_reference(&mut self) {
        self.tx_reference.clear();
    }

    // Param is passed by value, moved
    pub fn set_tx_reference(&mut self, v: ::std::string::String) {
        self.tx_reference = v;
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_tx_reference(&mut self) -> &mut ::std::string::String {
        &mut self.tx_reference
    }

    // Take field
    pub fn take_tx_reference(&mut self) -> ::std::string::String {
        ::std::mem::replace(&mut self.tx_reference, ::std::string::String::new())
    }

    // string tx_reference1 = 6;

    pub fn get_tx_reference1(&self) -> &str {
        &self.tx_reference1
    }
    pub fn clear_tx_reference1(&mut self) {
        self.tx_reference1.clear();
    }

    // Param is passed by value, moved
    pub fn set_tx_reference1(&mut self, v: ::std::string::String) {
        self.tx_reference1 = v;
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_tx_reference1(&mut self) -> &mut ::std::string::String {
        &mut self.tx_reference1
    }

    // Take field
    pub fn take_tx_reference1(&mut self) -> ::std::string::String {
        ::std::mem::replace(&mut self.tx_reference1, ::std::string::String::new())
    }

    // double amount = 7;

    pub fn get_amount(&self) -> f64 {
        self.amount
    }
    pub fn clear_amount(&mut self) {
        self.amount = 0.;
    }

    // Param is passed by value, moved
    pub fn set_amount(&mut self, v: f64) {
        self.amount = v;
    }

    // string status = 8;

    pub fn get_status(&self) -> &str {
        &self.status
    }
    pub fn clear_status(&mut self) {
        self.status.clear();
    }

    // Param is passed by value, moved
    pub fn set_status(&mut self, v: ::std::string::String) {
        self.status = v;
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_status(&mut self) -> &mut ::std::string::String {
        &mut self.status
    }

    // Take field
    pub fn take_status(&mut self) -> ::std::string::String {
        ::std::mem::replace(&mut self.status, ::std::string::String::new())
    }

    // string trx_type = 9;

    pub fn get_trx_type(&self) -> &str {
        &self.trx_type
    }
    pub fn clear_trx_type(&mut self) {
        self.trx_type.clear();
    }

    // Param is passed by value, moved
    pub fn set_trx_type(&mut self, v: ::std::string::String) {
        self.trx_type = v;
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_trx_type(&mut self) -> &mut ::std::string::String {
        &mut self.trx_type
    }

    // Take field
    pub fn take_trx_type(&mut self) -> ::std::string::String {
        ::std::mem::replace(&mut self.trx_type, ::std::string::String::new())
    }

    // string status_description = 10;

    pub fn get_status_description(&self) -> &str {
        &self.status_description
    }
    pub fn clear_status_description(&mut self) {
        self.status_description.clear();
    }

    // Param is passed by value, moved
    pub fn set_status_description(&mut self, v: ::std::string::String) {
        self.status_description = v;
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_status_description(&mut self) -> &mut ::std::string::String {
        &mut self.status_description
    }

    // Take field
    pub fn take_status_description(&mut self) -> ::std::string::String {
        ::std::mem::replace(&mut self.status_description, ::std::string::String::new())
    }

    // string trx_source = 11;

    pub fn get_trx_source(&self) -> &str {
        &self.trx_source
    }
    pub fn clear_trx_source(&mut self) {
        self.trx_source.clear();
    }

    // Param is passed by value, moved
    pub fn set_trx_source(&mut self, v: ::std::string::String) {
        self.trx_source = v;
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_trx_source(&mut self) -> &mut ::std::string::String {
        &mut self.trx_source
    }

    // Take field
    pub fn take_trx_source(&mut self) -> ::std::string::String {
        ::std::mem::replace(&mut self.trx_source, ::std::string::String::new())
    }

    // string biller_status = 12;

    pub fn get_biller_status(&self) -> &str {
        &self.biller_status
    }
    pub fn clear_biller_status(&mut self) {
        self.biller_status.clear();
    }

    // Param is passed by value, moved
    pub fn set_biller_status(&mut self, v: ::std::string::String) {
        self.biller_status = v;
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_biller_status(&mut self) -> &mut ::std::string::String {
        &mut self.biller_status
    }

    // Take field
    pub fn take_biller_status(&mut self) -> ::std::string::String {
        ::std::mem::replace(&mut self.biller_status, ::std::string::String::new())
    }

    // string country = 13;

    pub fn get_country(&self) -> &str {
        &self.country
    }
    pub fn clear_country(&mut self) {
        self.country.clear();
    }

    // Param is passed by value, moved
    pub fn set_country(&mut self, v: ::std::string::String) {
        self.country = v;
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_country(&mut self) -> &mut ::std::string::String {
        &mut self.country
    }

    // Take field
    pub fn take_country(&mut self) -> ::std::string::String {
        ::std::mem::replace(&mut self.country, ::std::string::String::new())
    }

    // double discount_amount = 14;

    pub fn get_discount_amount(&self) -> f64 {
        self.discount_amount
    }
    pub fn clear_discount_amount(&mut self) {
        self.discount_amount = 0.;
    }

    // Param is passed by value, moved
    pub fn set_discount_amount(&mut self, v: f64) {
        self.discount_amount = v;
    }

    // double amount_txn = 15;

    pub fn get_amount_txn(&self) -> f64 {
        self.amount_txn
    }
    pub fn clear_amount_txn(&mut self) {
        self.amount_txn = 0.;
    }

    // Param is passed by value, moved
    pub fn set_amount_txn(&mut self, v: f64) {
        self.amount_txn = v;
    }

    // string access_mode = 16;

    pub fn get_access_mode(&self) -> &str {
        &self.access_mode
    }
    pub fn clear_access_mode(&mut self) {
        self.access_mode.clear();
    }

    // Param is passed by value, moved
    pub fn set_access_mode(&mut self, v: ::std::string::String) {
        self.access_mode = v;
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_access_mode(&mut self) -> &mut ::std::string::String {
        &mut self.access_mode
    }

    // Take field
    pub fn take_access_mode(&mut self) -> ::std::string::String {
        ::std::mem::replace(&mut self.access_mode, ::std::string::String::new())
    }

    // int64 date = 17;

    pub fn get_date(&self) -> i64 {
        self.date
    }
    pub fn clear_date(&mut self) {
        self.date = 0;
    }

    // Param is passed by value, moved
    pub fn set_date(&mut self, v: i64) {
        self.date = v;
    }

    // int64 time = 18;

    pub fn get_time(&self) -> i64 {
        self.time
    }
    pub fn clear_time(&mut self) {
        self.time = 0;
    }

    // Param is passed by value, moved
    pub fn set_time(&mut self, v: i64) {
        self.time = v;
    }
}

impl ::protobuf::Message for OutputAccount {
    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(
        &mut self,
        is: &mut ::protobuf::CodedInputStream<'_>,
    ) -> ::protobuf::ProtobufResult<()> {
        while !is.eof()? {
            let (field_number, wire_type) = is.read_tag_unpack()?;
            match field_number {
                1 => {
                    if wire_type != ::protobuf::wire_format::WireTypeVarint {
                        return ::std::result::Result::Err(::protobuf::rt::unexpected_wire_type(
                            wire_type,
                        ));
                    }
                    let tmp = is.read_int64()?;
                    self.datetime = tmp;
                }
                2 => {
                    if wire_type != ::protobuf::wire_format::WireTypeFixed64 {
                        return ::std::result::Result::Err(::protobuf::rt::unexpected_wire_type(
                            wire_type,
                        ));
                    }
                    let tmp = is.read_double()?;
                    self.row_id = tmp;
                }
                3 => {
                    ::protobuf::rt::read_singular_proto3_string_into(
                        wire_type,
                        is,
                        &mut self.merchant_code,
                    )?;
                }
                4 => {
                    ::protobuf::rt::read_singular_proto3_string_into(
                        wire_type,
                        is,
                        &mut self.service_account_id,
                    )?;
                }
                5 => {
                    ::protobuf::rt::read_singular_proto3_string_into(
                        wire_type,
                        is,
                        &mut self.tx_reference,
                    )?;
                }
                6 => {
                    ::protobuf::rt::read_singular_proto3_string_into(
                        wire_type,
                        is,
                        &mut self.tx_reference1,
                    )?;
                }
                7 => {
                    if wire_type != ::protobuf::wire_format::WireTypeFixed64 {
                        return ::std::result::Result::Err(::protobuf::rt::unexpected_wire_type(
                            wire_type,
                        ));
                    }
                    let tmp = is.read_double()?;
                    self.amount = tmp;
                }
                8 => {
                    ::protobuf::rt::read_singular_proto3_string_into(
                        wire_type,
                        is,
                        &mut self.status,
                    )?;
                }
                9 => {
                    ::protobuf::rt::read_singular_proto3_string_into(
                        wire_type,
                        is,
                        &mut self.trx_type,
                    )?;
                }
                10 => {
                    ::protobuf::rt::read_singular_proto3_string_into(
                        wire_type,
                        is,
                        &mut self.status_description,
                    )?;
                }
                11 => {
                    ::protobuf::rt::read_singular_proto3_string_into(
                        wire_type,
                        is,
                        &mut self.trx_source,
                    )?;
                }
                12 => {
                    ::protobuf::rt::read_singular_proto3_string_into(
                        wire_type,
                        is,
                        &mut self.biller_status,
                    )?;
                }
                13 => {
                    ::protobuf::rt::read_singular_proto3_string_into(
                        wire_type,
                        is,
                        &mut self.country,
                    )?;
                }
                14 => {
                    if wire_type != ::protobuf::wire_format::WireTypeFixed64 {
                        return ::std::result::Result::Err(::protobuf::rt::unexpected_wire_type(
                            wire_type,
                        ));
                    }
                    let tmp = is.read_double()?;
                    self.discount_amount = tmp;
                }
                15 => {
                    if wire_type != ::protobuf::wire_format::WireTypeFixed64 {
                        return ::std::result::Result::Err(::protobuf::rt::unexpected_wire_type(
                            wire_type,
                        ));
                    }
                    let tmp = is.read_double()?;
                    self.amount_txn = tmp;
                }
                16 => {
                    ::protobuf::rt::read_singular_proto3_string_into(
                        wire_type,
                        is,
                        &mut self.access_mode,
                    )?;
                }
                17 => {
                    if wire_type != ::protobuf::wire_format::WireTypeVarint {
                        return ::std::result::Result::Err(::protobuf::rt::unexpected_wire_type(
                            wire_type,
                        ));
                    }
                    let tmp = is.read_int64()?;
                    self.date = tmp;
                }
                18 => {
                    if wire_type != ::protobuf::wire_format::WireTypeVarint {
                        return ::std::result::Result::Err(::protobuf::rt::unexpected_wire_type(
                            wire_type,
                        ));
                    }
                    let tmp = is.read_int64()?;
                    self.time = tmp;
                }
                _ => {
                    ::protobuf::rt::read_unknown_or_skip_group(
                        field_number,
                        wire_type,
                        is,
                        self.mut_unknown_fields(),
                    )?;
                }
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u32 {
        let mut my_size = 0;
        if self.datetime != 0 {
            my_size += ::protobuf::rt::value_size(
                1,
                self.datetime,
                ::protobuf::wire_format::WireTypeVarint,
            );
        }
        if self.row_id != 0. {
            my_size += 9;
        }
        if !self.merchant_code.is_empty() {
            my_size += ::protobuf::rt::string_size(3, &self.merchant_code);
        }
        if !self.service_account_id.is_empty() {
            my_size += ::protobuf::rt::string_size(4, &self.service_account_id);
        }
        if !self.tx_reference.is_empty() {
            my_size += ::protobuf::rt::string_size(5, &self.tx_reference);
        }
        if !self.tx_reference1.is_empty() {
            my_size += ::protobuf::rt::string_size(6, &self.tx_reference1);
        }
        if self.amount != 0. {
            my_size += 9;
        }
        if !self.status.is_empty() {
            my_size += ::protobuf::rt::string_size(8, &self.status);
        }
        if !self.trx_type.is_empty() {
            my_size += ::protobuf::rt::string_size(9, &self.trx_type);
        }
        if !self.status_description.is_empty() {
            my_size += ::protobuf::rt::string_size(10, &self.status_description);
        }
        if !self.trx_source.is_empty() {
            my_size += ::protobuf::rt::string_size(11, &self.trx_source);
        }
        if !self.biller_status.is_empty() {
            my_size += ::protobuf::rt::string_size(12, &self.biller_status);
        }
        if !self.country.is_empty() {
            my_size += ::protobuf::rt::string_size(13, &self.country);
        }
        if self.discount_amount != 0. {
            my_size += 9;
        }
        if self.amount_txn != 0. {
            my_size += 9;
        }
        if !self.access_mode.is_empty() {
            my_size += ::protobuf::rt::string_size(16, &self.access_mode);
        }
        if self.date != 0 {
            my_size +=
                ::protobuf::rt::value_size(17, self.date, ::protobuf::wire_format::WireTypeVarint);
        }
        if self.time != 0 {
            my_size +=
                ::protobuf::rt::value_size(18, self.time, ::protobuf::wire_format::WireTypeVarint);
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.get_unknown_fields());
        self.cached_size.set(my_size);
        my_size
    }

    fn write_to_with_cached_sizes(
        &self,
        os: &mut ::protobuf::CodedOutputStream<'_>,
    ) -> ::protobuf::ProtobufResult<()> {
        if self.datetime != 0 {
            os.write_int64(1, self.datetime)?;
        }
        if self.row_id != 0. {
            os.write_double(2, self.row_id)?;
        }
        if !self.merchant_code.is_empty() {
            os.write_string(3, &self.merchant_code)?;
        }
        if !self.service_account_id.is_empty() {
            os.write_string(4, &self.service_account_id)?;
        }
        if !self.tx_reference.is_empty() {
            os.write_string(5, &self.tx_reference)?;
        }
        if !self.tx_reference1.is_empty() {
            os.write_string(6, &self.tx_reference1)?;
        }
        if self.amount != 0. {
            os.write_double(7, self.amount)?;
        }
        if !self.status.is_empty() {
            os.write_string(8, &self.status)?;
        }
        if !self.trx_type.is_empty() {
            os.write_string(9, &self.trx_type)?;
        }
        if !self.status_description.is_empty() {
            os.write_string(10, &self.status_description)?;
        }
        if !self.trx_source.is_empty() {
            os.write_string(11, &self.trx_source)?;
        }
        if !self.biller_status.is_empty() {
            os.write_string(12, &self.biller_status)?;
        }
        if !self.country.is_empty() {
            os.write_string(13, &self.country)?;
        }
        if self.discount_amount != 0. {
            os.write_double(14, self.discount_amount)?;
        }
        if self.amount_txn != 0. {
            os.write_double(15, self.amount_txn)?;
        }
        if !self.access_mode.is_empty() {
            os.write_string(16, &self.access_mode)?;
        }
        if self.date != 0 {
            os.write_int64(17, self.date)?;
        }
        if self.time != 0 {
            os.write_int64(18, self.time)?;
        }
        os.write_unknown_fields(self.get_unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn get_cached_size(&self) -> u32 {
        self.cached_size.get()
    }

    fn get_unknown_fields(&self) -> &::protobuf::UnknownFields {
        &self.unknown_fields
    }

    fn mut_unknown_fields(&mut self) -> &mut ::protobuf::UnknownFields {
        &mut self.unknown_fields
    }

    fn as_any(&self) -> &dyn (::std::any::Any) {
        self as &dyn (::std::any::Any)
    }
    fn as_any_mut(&mut self) -> &mut dyn (::std::any::Any) {
        self as &mut dyn (::std::any::Any)
    }
    fn into_any(self: Box<Self>) -> ::std::boxed::Box<dyn (::std::any::Any)> {
        self
    }

    fn descriptor(&self) -> &'static ::protobuf::reflect::MessageDescriptor {
        Self::descriptor_static()
    }

    fn new() -> OutputAccount {
        OutputAccount::new()
    }

    fn descriptor_static() -> &'static ::protobuf::reflect::MessageDescriptor {
        static mut descriptor: ::protobuf::lazy::Lazy<::protobuf::reflect::MessageDescriptor> =
            ::protobuf::lazy::Lazy::INIT;
        unsafe {
            descriptor.get(|| {
                let mut fields = ::std::vec::Vec::new();
                fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<
                    _,
                    ::protobuf::types::ProtobufTypeInt64,
                >(
                    "datetime",
                    |m: &OutputAccount| &m.datetime,
                    |m: &mut OutputAccount| &mut m.datetime,
                ));
                fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<
                    _,
                    ::protobuf::types::ProtobufTypeDouble,
                >(
                    "row_id",
                    |m: &OutputAccount| &m.row_id,
                    |m: &mut OutputAccount| &mut m.row_id,
                ));
                fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<
                    _,
                    ::protobuf::types::ProtobufTypeString,
                >(
                    "merchant_code",
                    |m: &OutputAccount| &m.merchant_code,
                    |m: &mut OutputAccount| &mut m.merchant_code,
                ));
                fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<
                    _,
                    ::protobuf::types::ProtobufTypeString,
                >(
                    "service_account_id",
                    |m: &OutputAccount| &m.service_account_id,
                    |m: &mut OutputAccount| &mut m.service_account_id,
                ));
                fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<
                    _,
                    ::protobuf::types::ProtobufTypeString,
                >(
                    "tx_reference",
                    |m: &OutputAccount| &m.tx_reference,
                    |m: &mut OutputAccount| &mut m.tx_reference,
                ));
                fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<
                    _,
                    ::protobuf::types::ProtobufTypeString,
                >(
                    "tx_reference1",
                    |m: &OutputAccount| &m.tx_reference1,
                    |m: &mut OutputAccount| &mut m.tx_reference1,
                ));
                fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<
                    _,
                    ::protobuf::types::ProtobufTypeDouble,
                >(
                    "amount",
                    |m: &OutputAccount| &m.amount,
                    |m: &mut OutputAccount| &mut m.amount,
                ));
                fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<
                    _,
                    ::protobuf::types::ProtobufTypeString,
                >(
                    "status",
                    |m: &OutputAccount| &m.status,
                    |m: &mut OutputAccount| &mut m.status,
                ));
                fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<
                    _,
                    ::protobuf::types::ProtobufTypeString,
                >(
                    "trx_type",
                    |m: &OutputAccount| &m.trx_type,
                    |m: &mut OutputAccount| &mut m.trx_type,
                ));
                fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<
                    _,
                    ::protobuf::types::ProtobufTypeString,
                >(
                    "status_description",
                    |m: &OutputAccount| &m.status_description,
                    |m: &mut OutputAccount| &mut m.status_description,
                ));
                fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<
                    _,
                    ::protobuf::types::ProtobufTypeString,
                >(
                    "trx_source",
                    |m: &OutputAccount| &m.trx_source,
                    |m: &mut OutputAccount| &mut m.trx_source,
                ));
                fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<
                    _,
                    ::protobuf::types::ProtobufTypeString,
                >(
                    "biller_status",
                    |m: &OutputAccount| &m.biller_status,
                    |m: &mut OutputAccount| &mut m.biller_status,
                ));
                fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<
                    _,
                    ::protobuf::types::ProtobufTypeString,
                >(
                    "country",
                    |m: &OutputAccount| &m.country,
                    |m: &mut OutputAccount| &mut m.country,
                ));
                fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<
                    _,
                    ::protobuf::types::ProtobufTypeDouble,
                >(
                    "discount_amount",
                    |m: &OutputAccount| &m.discount_amount,
                    |m: &mut OutputAccount| &mut m.discount_amount,
                ));
                fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<
                    _,
                    ::protobuf::types::ProtobufTypeDouble,
                >(
                    "amount_txn",
                    |m: &OutputAccount| &m.amount_txn,
                    |m: &mut OutputAccount| &mut m.amount_txn,
                ));
                fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<
                    _,
                    ::protobuf::types::ProtobufTypeString,
                >(
                    "access_mode",
                    |m: &OutputAccount| &m.access_mode,
                    |m: &mut OutputAccount| &mut m.access_mode,
                ));
                fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<
                    _,
                    ::protobuf::types::ProtobufTypeInt64,
                >(
                    "date",
                    |m: &OutputAccount| &m.date,
                    |m: &mut OutputAccount| &mut m.date,
                ));
                fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<
                    _,
                    ::protobuf::types::ProtobufTypeInt64,
                >(
                    "time",
                    |m: &OutputAccount| &m.time,
                    |m: &mut OutputAccount| &mut m.time,
                ));
                ::protobuf::reflect::MessageDescriptor::new::<OutputAccount>(
                    "OutputAccount",
                    fields,
                    file_descriptor_proto(),
                )
            })
        }
    }

    fn default_instance() -> &'static OutputAccount {
        static mut instance: ::protobuf::lazy::Lazy<OutputAccount> = ::protobuf::lazy::Lazy::INIT;
        unsafe { instance.get(OutputAccount::new) }
    }
}

impl ::protobuf::Clear for OutputAccount {
    fn clear(&mut self) {
        self.datetime = 0;
        self.row_id = 0.;
        self.merchant_code.clear();
        self.service_account_id.clear();
        self.tx_reference.clear();
        self.tx_reference1.clear();
        self.amount = 0.;
        self.status.clear();
        self.trx_type.clear();
        self.status_description.clear();
        self.trx_source.clear();
        self.biller_status.clear();
        self.country.clear();
        self.discount_amount = 0.;
        self.amount_txn = 0.;
        self.access_mode.clear();
        self.date = 0;
        self.time = 0;
        self.unknown_fields.clear();
    }
}

impl ::std::fmt::Debug for OutputAccount {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for OutputAccount {
    fn as_ref(&self) -> ::protobuf::reflect::ReflectValueRef {
        ::protobuf::reflect::ReflectValueRef::Message(self)
    }
}

static file_descriptor_proto_data: &'static [u8] = b"\
    \n\x15recon_mobile_e2.proto\"\xc6\x04\n\rOutputAccount\x12\x1a\n\x08date\
    time\x18\x01\x20\x01(\x03R\x08datetime\x12\x15\n\x06row_id\x18\x02\x20\
    \x01(\x01R\x05rowId\x12#\n\rmerchant_code\x18\x03\x20\x01(\tR\x0cmerchan\
    tCode\x12,\n\x12service_account_id\x18\x04\x20\x01(\tR\x10serviceAccount\
    Id\x12!\n\x0ctx_reference\x18\x05\x20\x01(\tR\x0btxReference\x12#\n\rtx_\
    reference1\x18\x06\x20\x01(\tR\x0ctxReference1\x12\x16\n\x06amount\x18\
    \x07\x20\x01(\x01R\x06amount\x12\x16\n\x06status\x18\x08\x20\x01(\tR\x06\
    status\x12\x19\n\x08trx_type\x18\t\x20\x01(\tR\x07trxType\x12-\n\x12stat\
    us_description\x18\n\x20\x01(\tR\x11statusDescription\x12\x1d\n\ntrx_sou\
    rce\x18\x0b\x20\x01(\tR\ttrxSource\x12#\n\rbiller_status\x18\x0c\x20\x01\
    (\tR\x0cbillerStatus\x12\x18\n\x07country\x18\r\x20\x01(\tR\x07country\
    \x12'\n\x0fdiscount_amount\x18\x0e\x20\x01(\x01R\x0ediscountAmount\x12\
    \x1d\n\namount_txn\x18\x0f\x20\x01(\x01R\tamountTxn\x12\x1f\n\x0baccess_\
    mode\x18\x10\x20\x01(\tR\naccessMode\x12\x12\n\x04date\x18\x11\x20\x01(\
    \x03R\x04date\x12\x12\n\x04time\x18\x12\x20\x01(\x03R\x04timeb\x06proto3\
";

static mut file_descriptor_proto_lazy: ::protobuf::lazy::Lazy<
    ::protobuf::descriptor::FileDescriptorProto,
> = ::protobuf::lazy::Lazy::INIT;

fn parse_descriptor_proto() -> ::protobuf::descriptor::FileDescriptorProto {
    ::protobuf::parse_from_bytes(file_descriptor_proto_data).unwrap()
}

pub fn file_descriptor_proto() -> &'static ::protobuf::descriptor::FileDescriptorProto {
    unsafe { file_descriptor_proto_lazy.get(|| parse_descriptor_proto()) }
}
